name: 'Terraform'

on:
  push:
    branches:
    - dev
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Init
      id: init
      run: |
        export "TF_CLI_CONFIG_FILE=./.terraformrc"
        export "TF_WORKSPACE=${GITHUB_REF##*/}"
        echo "WORKSPACE: $TF_WORKSPACE"
        terraform init

    - name: Terraform Validate
      id: validate
      run: terraform validate

    - name: Terraform Plan
      id: plan
      run: |
        export "TF_WORKSPACE=${GITHUB_REF##*/}"
        terraform plan -no-color

    - name: Terraform Apply
      run: |
        export "TF_WORKSPACE=${GITHUB_REF##*/}"
        terraform apply -auto-approve

